Repository dalexhd/ft_irc, pull requests merged in 2022-04, with the labels that each got.

#3 Add socket listener
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  Makefile
  README.md
  includes/client.hpp
  includes/config.hpp
  includes/server.hpp
  main.cpp
  srcs/client.cpp
  srcs/server.cpp
Labels: feature, core

#4 feat: add commands documentation.
  README.md
Labels: documentation

#6 fix bad df while reading from fd.
  Makefile
  includes/client.hpp
  includes/server.hpp
  srcs/client.cpp
  srcs/server.cpp
Labels: bug

#7 feat: add initial commands structure.
  includes/Command.hpp
  includes/client.hpp
  includes/commands/Exit.hpp
  includes/commands/Info.hpp
  includes/commands/Ping.hpp
  includes/server.hpp
  main.cpp
  srcs/client.cpp
  srcs/server.cpp
Labels: feature

#9 feat: add msg split.
  Makefile
  README.md
  includes/Color.hpp
  includes/Command.hpp
  includes/Message.hpp
  includes/client.hpp
  includes/commands/Echo.hpp
  includes/commands/Exit.hpp
  includes/commands/Help.hpp
  includes/commands/Info.hpp
  includes/commands/Ping.hpp
  includes/server.hpp
  srcs/Message.cpp
  srcs/client.cpp
  srcs/server.cpp
Labels: feature

#8 readme refactor
  README.md
Labels: documentation

#10 fix: memory related issues.
  srcs/server.cpp
Labels: bug

#12 feat: add ope role.
  Makefile
  includes/Command.hpp
  includes/client.hpp
  includes/commands/Ban.hpp
  includes/commands/Ope.hpp
  srcs/client.cpp
  srcs/server.cpp
Labels: feature
